DELETE FROM `MJ_FAVORITE_ARTIST`;
DELETE FROM `MJ_RATING`;
DELETE FROM `MJ_PERFORMANCE`;
DELETE FROM `MJ_ARTIST_GROUP`;
DELETE FROM `MJ_STR_AUTH`;
DELETE FROM `MJ_STR_DL`;
DELETE FROM `MJ_ARTISTS`;
DELETE FROM `MJ_USERS`;
DELETE FROM `MJ_SONGS`;
DELETE FROM `MJ_ALBUMS`;
DELETE FROM `MJ_GROUPS`;
DELETE FROM `MJ_GENRES`;

